feature/create-letters-show
utfpr-gp/natal-dos-sonhos-app pull request #9
Opened 2023-06-20 00:00 UTC by camilaesouza

### **O que foi feito**
- Tela de visualização da carta

### **Para testar:**
/cartas > acessar uma carta (botão contribuir)

### **Observação**
- Dados da escola não estavam disponíveis, seria necessário uma conversa com quem está com a tarefa referente a escola, para verificação dos dados e como eles ficariam. Foi utilizado dados fixos enquanto isso!

2023-06-20 21:15 UTC, ronifabio requested changes
- Colocar uma margem superior a imagem na carta. 
- 
![image](https://github.com/utfpr-gp/natal-dos-sonhos-app/assets/3456733/690ee09b-6d31-4469-84df-3208ba4d8c39)
- A página de detalhes não está responsiva
- 
![image](https://github.com/utfpr-gp/natal-dos-sonhos-app/assets/3456733/6964b882-2c2c-4a6d-97f4-d92b046920c2)
- deixar o componente de contagem regressiva apenas na tela inicial, não precisa apresentar na tela de cartas: app-christmas-countdown
- Colocar um título em <h1> para suas páginas. Na tela /inicio ou /cartas, colocar o título "Cartas de Natal".
- No /inicio, não está responsivo e não tem class CSS container para espaçamento lateral.
- Em /cartas, está responsivo e tem espaçamento via container.
- 
![image](https://github.com/utfpr-gp/natal-dos-sonhos-app/assets/3456733/f18c77db-644a-490f-9b2a-67385f6604d3)

2023-06-20 21:15 UTC, ronifabio commented on db.json
> +      "imageURL": "https://www.wikihow.com/images_en/thumb/8/84/Sign-a-Love-Letter-Step-1-Version-4.jpg/v4-460px-Sign-a-Love-Letter-Step-1-Version-4.jpg.webp",
Subir uma imagem para o cloudinary, pode ser manualmente via browser. Usar a URL do cloudinary ao invés desta URL da Internet.

2023-06-20 21:15 UTC, ronifabio commented on db.json
> +      "imageURL": "https://www.wikihow.com/images_en/thumb/8/84/Sign-a-Love-Letter-Step-1-Version-4.jpg/v4-460px-Sign-a-Love-Letter-Step-1-Version-4.jpg.webp",
A imagem precisa ser do produto, não da carta.

2023-06-20 21:15 UTC, ronifabio commented on db.json
> +      "imageURL": "https://www.wikihow.com/images_en/thumb/8/84/Sign-a-Love-Letter-Step-1-Version-4.jpg/v4-460px-Sign-a-Love-Letter-Step-1-Version-4.jpg.webp",
Faça para todas imagens usadas nestas páginas

2023-06-24 18:06 UTC, camilaesouza commented on db.json
> +      "imageURL": "https://www.wikihow.com/images_en/thumb/8/84/Sign-a-Love-Letter-Step-1-Version-4.jpg/v4-460px-Sign-a-Love-Letter-Step-1-Version-4.jpg.webp",
Sobre a imagem do produto e da cartas. Existem os dois, no layout do trello é possível ver, temos tanto a foto da carta quando do produto. Logo em letters é a foto da carta e letters.produt a foto do produto.

Também apenas coloquei as imagens para teste, esqueci de alterar o arquivo de db após finalizar.

2023-06-27 15:01 UTC, ronifabio requested changes
Na tela /inicio, ou seja, na LandPage, colocar as últimas 4 cartas que receberam doações e também um link Ver Tudo para abrir a página /cartas.
Opcionalmente, pode criar outras categorias de 4 cartas, como por exemplo, as últimas cadastradas, as últimas finalizadas, todas elas com o link Ver Tudo.
Segue o exemplo do uso do link Ver Tudo na Shopee
![image](https://github.com/utfpr-gp/natal-dos-sonhos-app/assets/3456733/7c0912e5-c097-4981-8eec-6247045e93f3)

2023-06-28 22:55 UTC, camilaesouza commented
> Na tela /inicio, ou seja, na LandPage, colocar as últimas 4 cartas que receberam doações e também um link Ver Tudo para abrir a página /cartas. Opcionalmente, pode criar outras categorias de 4 cartas, como por exemplo, as últimas cadastradas, as últimas finalizadas, todas elas com o link Ver Tudo. Segue o exemplo do uso do link Ver Tudo na Shopee ![image](https://user-images.githubusercontent.com/3456733/249194935-7c0912e5-c097-4981-8eec-6247045e93f3.png)

Como a parte de doações ficou com o mateus, não sei como ficou a parte de estrutura de doações, então adicionei uma flag nas cartas dateOfLastDonation, acredito que conforme doações, pode ser atualizado a data, ai temos a informação para filtrar as cartas pelas ultimas que tiveram doações.  Adicionei outras duas categorias, cartas pelas ultimas cadastradas e pela data de finalização

2023-06-29 15:08 UTC, ronifabio requested changes
- Ajustar os paineis de destaque para aparecerem os cartões mesmo, não só a imagem do produto. Está estranho assim.

![image](https://github.com/utfpr-gp/natal-dos-sonhos-app/assets/3456733/cfd1a1c5-cb22-4f71-ad30-a798ff4f1c21)
- Mostre os cartões desta forma também na tela inicial, ou seja, nos paineis de destaque.

![image](https://github.com/utfpr-gp/natal-dos-sonhos-app/assets/3456733/b1f5bc1f-5eac-49a3-a172-804d150c2a8b)
- Com isso, o usuário vê algumas 4 cartas em cada painel de destaque e clica em Ver Tudo para ver todas as cartas.
- Trocar o título h5 de SERVIÇOS por CARTAS.
- Ajustar a tela inicial para não aparecer estas cartas do João Paulo, que acredito que é algo antigo, de outra turma. Remova este componente.
![image](https://github.com/utfpr-gp/natal-dos-sonhos-app/assets/3456733/7359f6ae-c842-4255-941a-9719974e3d1e)

2023-07-05 16:09 UTC, merged